name: wellnessbridge
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0' # Adjusted SDK version to be more flexible

dependencies:
  flutter:
    sdk: flutter
  http: 0.13.6 # Updated to a slightly newer version for consistency
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  connectivity_plus: ^6.0.1 # Essential for checking network status for sync
  idb_shim: ^2.4.1+1
  hive: ^2.2.3  # Works on all platforms
  hive_flutter: ^1.1.0
  google_maps_webservice: ^0.0.20-nullsafety.2 # For Google Places API
  timezone: ^0.9.2
# firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^18.0.1

  
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.4.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/uploads/
    - assets/icons/