// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVknSNULVDrolcZIjQe6T9SyD9yRZkoBM',
    appId: '1:261003038203:android:2fca59ae76b18053084f5e',
    messagingSenderId: '261003038203',
    projectId: 'wellnessbridge-f26a4',
    storageBucket: 'wellnessbridge-f26a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVknSNULVDrolcZIjQe6T9SyD9yRZkoBM',
    appId: '1:261003038203:android:2fca59ae76b18053084f5e',
    messagingSenderId: '261003038203',
    projectId: 'wellnessbridge-f26a4',
    storageBucket: 'wellnessbridge-f26a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVknSNULVDrolcZIjQe6T9SyD9yRZkoBM',
    appId: '1:261003038203:ios:2fca59ae76b18053084f5e',
    messagingSenderId: '261003038203',
    projectId: 'wellnessbridge-f26a4',
    storageBucket: 'wellnessbridge-f26a4.firebasestorage.app',
    iosBundleId: 'com.example.wellnessbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVknSNULVDrolcZIjQe6T9SyD9yRZkoBM',
    appId: '1:261003038203:ios:2fca59ae76b18053084f5e',
    messagingSenderId: '261003038203',
    projectId: 'wellnessbridge-f26a4',
    storageBucket: 'wellnessbridge-f26a4.firebasestorage.app',
    iosBundleId: 'com.example.wellnessbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVknSNULVDrolcZIjQe6T9SyD9yRZkoBM',
    appId: '1:261003038203:web:2fca59ae76b18053084f5e',
    messagingSenderId: '261003038203',
    projectId: 'wellnessbridge-f26a4',
    storageBucket: 'wellnessbridge-f26a4.firebasestorage.app',
  );
}
